/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utils;

import com.mycompany.presentacionfaceboot.FrmEditarComentario;
import com.mycompany.presentacionfaceboot.FrmEliminarComentario;
import dominio.Comentario;
import dominio.Usuario;
import interfaces.IProxy;
import java.awt.Dimension;
import java.util.Calendar;

/**
 *
 * @author Gael
 */
public class ComentarioPublicacion extends javax.swing.JPanel {
    private Usuario usuario;
    private Comentario comentario;
    private IProxy proxy;
    /**
     * Creates new form Comentario
     */
    public ComentarioPublicacion(Usuario usuario, Comentario comentario, IProxy proxy) {
        initComponents();
        this.usuario= usuario;
        this.comentario= comentario;
        this.proxy=proxy;
        this.actualizarContenido();
        this.init();
    }

    public void actualizarContenido() {
        this.lblUsuario.setText(comentario.getUsuario().getUsuario());
        this.lblFecha.setText(comentario.getFechaCreacion().get(Calendar.DAY_OF_MONTH)+"/"+(comentario.getFechaCreacion().get(Calendar.MONTH)+1)+"/"+comentario.getFechaCreacion().get(Calendar.YEAR));
//        this.txtpnContenido.setText(textoPlano);
//        this.repaint();
//        this.revalidate();
   
        this.pnlComentario.setText(comentario.getContenido().getTextoPlano());
        this.pnlComentario.repaint();
        this.pnlComentario.revalidate();
        
        if(usuario.getId()!=comentario.getUsuario().getId()){
            this.pnlOpciones.setVisible(false);
        }
   
        this.repaint();
        this.revalidate();

    }
    
     public void init(){
     this.pnlTodoComentario.setPreferredSize(new Dimension(482, 115));
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTodoComentario = new javax.swing.JPanel();
        pnlOpciones = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlComentario = new javax.swing.JTextPane();
        pnlDatos = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 217, 183));
        setForeground(new java.awt.Color(255, 217, 183));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnlTodoComentario.setBackground(new java.awt.Color(255, 217, 183));
        pnlTodoComentario.setForeground(new java.awt.Color(255, 217, 183));

        pnlOpciones.setBackground(new java.awt.Color(255, 217, 183));

        btnEditar.setBackground(new java.awt.Color(240, 115, 0));
        btnEditar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlComentario.setEditable(false);
        pnlComentario.setBackground(new java.awt.Color(255, 233, 214));
        pnlComentario.setBorder(null);
        pnlComentario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlComentario.setForeground(new java.awt.Color(204, 88, 3));
        jScrollPane1.setViewportView(pnlComentario);

        pnlDatos.setBackground(new java.awt.Color(255, 217, 183));

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(204, 88, 3));
        lblFecha.setText("22/22/22");

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(204, 88, 3));
        lblUsuario.setText("Juan");
        lblUsuario.setToolTipText("");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(28, 28, 28)
                .addComponent(lblFecha)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(lblUsuario)))
        );

        javax.swing.GroupLayout pnlTodoComentarioLayout = new javax.swing.GroupLayout(pnlTodoComentario);
        pnlTodoComentario.setLayout(pnlTodoComentarioLayout);
        pnlTodoComentarioLayout.setHorizontalGroup(
            pnlTodoComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTodoComentarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTodoComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTodoComentarioLayout.createSequentialGroup()
                        .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        pnlTodoComentarioLayout.setVerticalGroup(
            pnlTodoComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTodoComentarioLayout.createSequentialGroup()
                .addGroup(pnlTodoComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTodoComentarioLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTodoComentarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlTodoComentario);
    }// </editor-fold>//GEN-END:initComponents


    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        FrmEditarComentario editar= new FrmEditarComentario(this.usuario, this.proxy, this.comentario);
        editar.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        FrmEliminarComentario eliminar= new FrmEliminarComentario(this.usuario, this.proxy, this.comentario);
        eliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextPane pnlComentario;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlTodoComentario;
    // End of variables declaration//GEN-END:variables
}
