/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utils;

import dominio.*;
import interfaces.IProxy;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 * Clase utilizada para construir la publicación completa.
 *
 * @author Equipo broker
 */
public class PublicacionCompleta extends javax.swing.JPanel {

    /**
     * Usuario con el que se construye el componente.
     */
    private Usuario usuario;
    /**
     * Publicación con el que se construye el componente.
     */
    private Publicacion publicacion;
    /**
     * Instancia del proxy que utiliza el cliente.
     */
    private IProxy proxy;

    /**
     * Constructor que inicializa los componentes y atributos del panel.
     *
     * @param usuario Usuario con el que se construye el componente.
     * @param publicacion Publicación con el que se construye el componente.
     * @param proxy Instancia del proxy que utiliza el cliente.
     */
    public PublicacionCompleta(Usuario usuario, Publicacion publicacion, IProxy proxy) {
        initComponents();
        this.usuario = usuario;
        this.publicacion = publicacion;
        this.proxy = proxy;
        this.actualizarContenido();
    }

    /**
     * Método que actualiza el contenido del panel.
     */
    public void actualizarContenido() {
        CabeceraPublicacion cabeceraPublicacion = new CabeceraPublicacion(this.usuario, this.publicacion, this.proxy);

//        cabeceraPublicacion.init(usuario, fecha);
        ContenidoPublicacion contenidoPublicacion = new ContenidoPublicacion();

        contenidoPublicacion.init(publicacion.getContenido().getTextoPlano(), publicacion.getContenido().getImagen(), publicacion.getHashtags());

        Comentarios comentarios = new Comentarios(this.usuario, this.publicacion, this.proxy);
        Comentar comentar = new Comentar(this.usuario, this.publicacion, this.proxy);

        this.add(cabeceraPublicacion);
        this.add(contenidoPublicacion);
        this.add(comentarios);
        this.add(comentar);
        this.repaint();
        this.revalidate();

    }

    /**
     * Método que actualiza el contenido del panel cuando se edita una
     * publicación.
     */
    public void actualizarEdicionContenido() {
        ContenidoPublicacion contenidoPublicacion = new ContenidoPublicacion();
        contenidoPublicacion.init(publicacion.getContenido().getTextoPlano(), publicacion.getContenido().getImagen(), publicacion.getHashtags());
        Comentarios comentarios = new Comentarios(this.usuario, this.publicacion, this.proxy);
        Comentar comentar = new Comentar(this.usuario, this.publicacion, this.proxy);

        this.remove(1);
        this.add(contenidoPublicacion, 1);
        this.remove(2);
        this.add(comentarios, 2);
        this.remove(3);
        this.add(comentar, 3);

        this.repaint();
        this.revalidate();
    }

    /**
     * Método para obtener la publicación.
     *
     * @return publicación.
     */
    public Publicacion getPublicacion() {
        return publicacion;
    }

    /**
     * Método para establecer la publicación.
     *
     * @param publicacion publicación.
     */
    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 217, 183));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 189, 130)));
        setForeground(new java.awt.Color(255, 217, 183));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
