/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacionfaceboot;

/**
 *
 * @author Jarol
 */
public class frmEditarPerfil extends javax.swing.JFrame {

    /**
     * Creates new form frmEditarPerfil
     */
    public frmEditarPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        comboBoxSexo = new javax.swing.JComboBox<>();
        fechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        btnGuardarCambios = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 217, 183));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha de nacimiento");
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 250, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        jLabel2.setText("Editar perfil");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 250, 30));

        jLabel3.setText("Usuario");
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 250, 30));

        jLabel5.setText("Contraseña");
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 250, 30));

        jLabel7.setText("Sexo");
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 250, 30));
        fondo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 340, 30));
        fondo.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 340, 30));

        comboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino ", "Femenino" }));
        fondo.add(comboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 340, 30));
        fondo.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 340, 30));

        btnGuardarCambios.setText("Guardar cambios");
        btnGuardarCambios.setActionCommand("");
        btnGuardarCambios.setBackground(new java.awt.Color(240, 115, 0));
        btnGuardarCambios.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnGuardarCambios.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        fondo.add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 140, 40));

        btnCancelar.setText("Cancelar");
        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        fondo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JComboBox<String> comboBoxSexo;
    private com.github.lgooddatepicker.components.DatePicker fechaNacimiento;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
