/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.presentacionfaceboot;

import dominio.Mensaje;
import dominio.Usuario;
import excepciones.ErrorBusquedaUsuarioException;
import excepciones.ErrorEnviarMensajeException;
import interfaces.IProxy;
import javax.swing.JOptionPane;

/**
 *
 * @author Jarol
 */
public class FrmNotificar extends javax.swing.JFrame {
    private Usuario usuario;
    private IProxy proxy;
    
    /**
     * Creates new form FrmNotificar
     */
    public FrmNotificar(Usuario usuario, IProxy proxy) {
        initComponents();
        this.usuario= usuario;
        this.proxy= proxy;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnEnviarMensaje = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtDestinatario = new javax.swing.JTextField();
        rbnSMS = new javax.swing.JRadioButton();
        rbnEmail = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Faceboot - Enviar Mensaje");
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 217, 183));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Metodo de  envío");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setText("Enviar mensaje");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Destinatario");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);
        jScrollPane1.setViewportView(txtMensaje);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 310, 190));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Mensaje");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        btnEnviarMensaje.setBackground(new java.awt.Color(240, 115, 0));
        btnEnviarMensaje.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnEnviarMensaje.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarMensaje.setText("Enviar");
        btnEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensajeActionPerformed(evt);
            }
        });
        fondo.add(btnEnviarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 140, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        fondo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 150, 40));
        fondo.add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        rbnSMS.setText("SMS");
        fondo.add(rbnSMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        rbnEmail.setText("Email");
        fondo.add(rbnEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmMuro muro= new FrmMuro(usuario, proxy);
        muro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensajeActionPerformed
        if(rbnSMS.isSelected()==false && rbnEmail.isSelected()==false){
            this.mostrarError("No se ha seleccionado un método de envío");
            return;
        }
        
        Mensaje mensaje= new Mensaje();
        String textoPlano= this.txtMensaje.getText();
        boolean sms= this.rbnSMS.isSelected();
        boolean email= this.rbnEmail.isSelected();
        mensaje.setTextoPlano(textoPlano);
        mensaje.setMensajeSMS(sms);
        mensaje.setMensajeEmail(email);
        mensaje.setUsuario(usuario);
        
        try{
            Usuario destinatario= new Usuario(this.txtDestinatario.getText());
            
            Usuario usuarioDestinatario= this.proxy.consultarUsuarioNombre(destinatario);
            
            mensaje.setReceptor(usuarioDestinatario);
            
            Mensaje respuesta= proxy.enviarMensaje(mensaje);
            this.mostrarMensaje("Se envió correctamente el mensaje");
        } catch (ErrorBusquedaUsuarioException e){
            this.mostrarMensaje(e.getMessage());
        } catch (ErrorEnviarMensajeException e){
            this.mostrarMensaje(e.getMessage());
        }
    }//GEN-LAST:event_btnEnviarMensajeActionPerformed

    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Respuesta del servidor", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void mostrarError(String error) {
        JOptionPane.showMessageDialog(this, error, "Error!...", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviarMensaje;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbnEmail;
    private javax.swing.JRadioButton rbnSMS;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextArea txtMensaje;
    // End of variables declaration//GEN-END:variables
}
